# Generated by Django 4.1.3 on 2022-12-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название теста')),
                ('time', models.TimeField(verbose_name='Время выполнения')),
                ('deadline', models.DateTimeField(verbose_name='Срок сдачи')),
                ('boss', models.ImageField(upload_to='', verbose_name='Босс')),
                ('five', models.PositiveIntegerField(verbose_name='Количество баллов для оценки 5')),
                ('four', models.PositiveIntegerField(verbose_name='Количество баллов для оценки 4')),
                ('three', models.PositiveIntegerField(verbose_name='Количество баллов для оценки 3')),
                ('two', models.PositiveIntegerField(verbose_name='Количество баллов для оценки 2')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Поле для ввода вопроса')),
                ('first_answer', models.CharField(max_length=250, verbose_name='Вариант ответа №1')),
                ('second_answer', models.CharField(max_length=250, verbose_name='Вариант ответа №2')),
                ('third_answer', models.CharField(max_length=250, verbose_name='Вариант ответа №3')),
                ('four_answer', models.CharField(max_length=250, verbose_name='Вариант ответа №4')),
                ('number_correct_answer', models.PositiveIntegerField(verbose_name='Номер правильного ответа')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.test')),
            ],
        ),
    ]
