# Generated by Django 4.1.3 on 2023-05-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tasks',
        ),
        migrations.AddField(
            model_name='test',
            name='group',
            field=models.ManyToManyField(blank=True, to='teacher.group'),
        ),
    ]
