# Generated by Django 4.1.3 on 2022-12-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='difficulty',
            field=models.PositiveIntegerField(null=True, verbose_name='Сложность'),
        ),
    ]
