# Generated by Django 4.1.3 on 2023-05-21 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_choice_question_delete_answer_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='main/static/photos/enemy/%Y/%m/%d')),
                ('name', models.CharField(default='Hero', max_length=100)),
                ('health', models.PositiveIntegerField(default=100, verbose_name='Здоровье')),
                ('power', models.PositiveIntegerField(default=5, verbose_name='Сила')),
                ('resistance', models.IntegerField(default=0, verbose_name='Стойкость')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.boss'),
        ),
    ]
