# Generated by Django 4.1.3 on 2022-12-13 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_test_deadline_test_date_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='boss',
        ),
    ]
