# Generated by Django 3.1.14 on 2023-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'мужчина'), ('F', 'женщина')], max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, choices=[('Екатеринбург', 'Екатеринбург'), ('Москва', 'Москва'), ('Санкт-Петербург', 'Санкт-Петербург')], max_length=50, null=True, verbose_name='Место учебы'),
        ),
    ]
