export interface ITest {
    "id": number,
    "owner_name": string,
    "title": string,
    "subject": string,
    "text": string,
    "difficulty": number,
    "time": string,
    "time_deadline": string,
    "date_deadline": string,
    "five": number,
    "four": number,
    "three": number,
    "two": number,
    "owner": number,
    "group": number[],
}
