# Generated by Django 4.1.3 on 2023-01-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account_Statistics',
        ),
    ]
