# Generated by Django 4.1.7 on 2023-03-03 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Statistics',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('lvl', models.PositiveIntegerField(default=0, verbose_name='Уровень')),
                ('groups', models.ManyToManyField(blank=True, to='teacher.group')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
    ]
