# Generated by Django 3.1.14 on 2023-06-08 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20230524_1501'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='main/static/photos/hero/')),
                ('name', models.CharField(default='Hero', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=300, verbose_name='ФИО')),
                ('test_name', models.CharField(default='', max_length=400, verbose_name='Название теста')),
                ('count_correct', models.IntegerField(default=0, verbose_name='Количество верных ответов')),
                ('grades', models.IntegerField(default=0, verbose_name='Оценка')),
                ('count_points', models.IntegerField(default=0, verbose_name='Количество заработнанных баллов')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.account')),
                ('name', models.CharField(default='Protagonist', max_length=100)),
                ('health', models.PositiveIntegerField(default=100, verbose_name='Здоровье')),
                ('endurance', models.PositiveIntegerField(default=5, verbose_name='Выносливость')),
                ('power', models.PositiveIntegerField(default=5, verbose_name='Сила')),
                ('resistance', models.IntegerField(default=0, verbose_name='Стойкость')),
                ('up_score', models.PositiveIntegerField(default=0, verbose_name='Очки навыков')),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='student.hero')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_answer', models.IntegerField()),
                ('lock_other', models.BooleanField(default=False)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.question')),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatistics',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='account.account')),
                ('user_name', models.CharField(default='', max_length=300, verbose_name='ФИО')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='Баланс')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('lvl', models.PositiveIntegerField(default=0, verbose_name='Уровень')),
                ('groups', models.ManyToManyField(blank=True, to='teacher.Group')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
    ]
