# Generated by Django 4.1.3 on 2023-01-09 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_account_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Statistics',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Очки')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт')),
                ('lvl', models.PositiveIntegerField(default=0, verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
