# Generated by Django 4.1.3 on 2023-01-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_statistics',
            name='groups',
            field=models.ManyToManyField(to='teacher.group'),
        ),
    ]
