# Generated by Django 4.1.3 on 2023-04-17 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type_equipment', models.CharField(choices=[('wp', 'weapon'), ('hm', 'helmet'), ('sp', 'shoulder_pads'), ('bp', 'breastplate'), ('gl', 'gloves'), ('tr', 'trousers'), ('sh', 'shoes')], max_length=2)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='Hero', max_length=100)),
                ('health', models.PositiveIntegerField(default=100, verbose_name='Здоровье')),
                ('endurance', models.PositiveIntegerField(default=5, verbose_name='Выносливость')),
                ('power', models.PositiveIntegerField(default=5, verbose_name='Сила')),
                ('dexterity', models.PositiveIntegerField(default=7, verbose_name='Ловкость')),
                ('resistance', models.IntegerField(default=0, verbose_name='Стойкость')),
                ('up_score', models.PositiveIntegerField(default=0, verbose_name='Очки навыков')),
            ],
            options={
                'verbose_name': 'Персонаж',
                'verbose_name_plural': 'Персонажи',
            },
        ),
        migrations.AddField(
            model_name='account_statistics',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ManyToManyField(blank=True, to='student.item')),
            ],
            options={
                'verbose_name': 'Инвентарь',
                'verbose_name_plural': 'Инвентарь',
            },
        ),
    ]
