# Generated by Django 3.1.14 on 2023-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0002_auto_20230528_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='test',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test',
            field=models.ManyToManyField(to='teacher.Test'),
        ),
    ]
