# Generated by Django 4.1.3 on 2023-01-09 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_account_statistics_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_statistics',
            options={'verbose_name': 'Статистика пользователя', 'verbose_name_plural': 'Статистика пользователей'},
        ),
    ]
