# Generated by Django 4.1.3 on 2023-05-10 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_choice_question_delete_answer_delete_choice'),
        ('student', '0003_test_record_choice_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.question'),
        ),
    ]
