# Generated by Django 3.1.14 on 2023-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_auto_20230528_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrecord',
            name='test',
            field=models.ManyToManyField(null=True, to='teacher.Test'),
        ),
    ]
