# Generated by Django 3.1.14 on 2023-05-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0004_auto_20230528_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testrecord',
            name='test',
        ),
        migrations.AddField(
            model_name='testrecord',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.test'),
        ),
    ]
