# Generated by Django 3.1.14 on 2023-05-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20230528_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='grades',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
