# Generated by Django 4.1.3 on 2023-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_test_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='number_answer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
