# Generated by Django 3.1.14 on 2023-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_testrecord_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='user_name',
            field=models.CharField(default='', max_length=100, verbose_name='ФИО'),
        ),
    ]
