# Generated by Django 4.1.3 on 2023-05-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_choice_number_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='title',
        ),
    ]
