# Generated by Django 4.1.3 on 2023-05-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_remove_choice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='points',
            field=models.IntegerField(),
        ),
    ]
