# Generated by Django 3.1.14 on 2023-05-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_testrecord_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='test_name',
            field=models.CharField(default='', max_length=400, verbose_name='Название теста'),
        ),
    ]
