# Generated by Django 4.1.3 on 2023-05-16 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_choice_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='points',
        ),
        migrations.AddField(
            model_name='test_record',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
