# Generated by Django 3.1.14 on 2023-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_testrecord_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatistics',
            name='user_name',
            field=models.CharField(default='', max_length=300, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='testrecord',
            name='user_name',
            field=models.CharField(default='', max_length=300, verbose_name='ФИО'),
        ),
    ]
