# Generated by Django 4.1.3 on 2023-05-21 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_remove_choice_points_test_record_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protagonist',
            name='photo',
            field=models.ImageField(blank=True, upload_to='main/static/photos/heroes/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='test_record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
